### ISSUE TITLE
add topics

### ISSUE THREAD

**Issue by Beliavsky** [BerriJ/sstudentt#395]
I suggest adding the topics `statistics`, `probability-distribution`, `student-t` in the About section at https://github.com/BerriJ/sstudentt

**Comment by BerriJ** [comment]
Hi,
Thanks for making this suggestion. Could you explain a little bit more what you mean?
Do you propose adding keywords in a new "About" Section? Where should this section be placed?

**Comment by Beliavsky** [comment]
Please see https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/classifying-your-repository-with-topics

**Comment by BerriJ** [comment]
Thanks again. Done :+1:
